tasks:
  - name: Add daily cloud service summary
    id: daily_cloud_service_summary
    uses: "@modules/resource"
    spec:
      resource_type: statistics.Schedule
      data:
        domain_id: ${{ tasks.user_domain.output.domain_id }}
        topic: daily_cloud_service_summary
        schedule:
          hours:
            - 1
        options:
          aggregate:
          - query:
              extend_data:
                label: Server
              query:
                aggregate:
                - group:
                    fields:
                    - name: value
                      operator: count
                    keys:
                    - key: project_id
                      name: project_id
                    - key: cloud_service_type
                      name: cloud_service_type
                    - key: cloud_service_group
                      name: cloud_service_group
                    - key: provider
                      name: provider
                filter:
                - key: ref_cloud_service_type.is_primary
                  operator: eq
                  value: true
                - key: ref_cloud_service_type.labels
                  operator: eq
                  value: Server
              resource_type: inventory.CloudService
          - concat:
              extend_data:
                label: Database
              query:
                aggregate:
                - group:
                    fields:
                    - name: value
                      operator: count
                    keys:
                    - key: project_id
                      name: project_id
                    - key: cloud_service_type
                      name: cloud_service_type
                    - key: cloud_service_group
                      name: cloud_service_group
                    - key: provider
                      name: provider
                filter:
                - key: ref_cloud_service_type.is_primary
                  operator: eq
                  value: true
                - key: ref_cloud_service_type.labels
                  operator: eq
                  value: Database
              resource_type: inventory.CloudService
          - concat:
              extend_data:
                label: Container
              query:
                aggregate:
                - group:
                    fields:
                    - name: value
                      operator: count
                    keys:
                    - key: project_id
                      name: project_id
                    - key: cloud_service_type
                      name: cloud_service_type
                    - key: cloud_service_group
                      name: cloud_service_group
                    - key: provider
                      name: provider
                filter:
                - key: ref_cloud_service_type.is_primary
                  operator: eq
                  value: true
                - key: ref_cloud_service_type.labels
                  operator: eq
                  value: Container
              resource_type: inventory.CloudService
          - concat:
              extend_data:
                label: Networking
              query:
                aggregate:
                - group:
                    fields:
                    - name: value
                      operator: count
                    keys:
                    - key: project_id
                      name: project_id
                    - key: cloud_service_type
                      name: cloud_service_type
                    - key: cloud_service_group
                      name: cloud_service_group
                    - key: provider
                      name: provider
                filter:
                - key: ref_cloud_service_type.is_primary
                  operator: eq
                  value: true
                - key: ref_cloud_service_type.labels
                  operator: eq
                  value: Networking
              resource_type: inventory.CloudService
          - concat:
              extend_data:
                label: Security
              query:
                aggregate:
                - group:
                    fields:
                    - name: value
                      operator: count
                    keys:
                    - key: project_id
                      name: project_id
                    - key: cloud_service_type
                      name: cloud_service_type
                    - key: cloud_service_group
                      name: cloud_service_group
                    - key: provider
                      name: provider
                filter:
                - key: ref_cloud_service_type.is_primary
                  operator: eq
                  value: true
                - key: ref_cloud_service_type.labels
                  operator: eq
                  value: Security
              resource_type: inventory.CloudService
          - concat:
              extend_data:
                label: Analytics
              query:
                aggregate:
                - group:
                    fields:
                    - name: value
                      operator: count
                    keys:
                    - key: project_id
                      name: project_id
                    - key: cloud_service_type
                      name: cloud_service_type
                    - key: cloud_service_group
                      name: cloud_service_group
                    - key: provider
                      name: provider
                filter:
                - key: ref_cloud_service_type.is_primary
                  operator: eq
                  value: true
                - key: ref_cloud_service_type.labels
                  operator: eq
                  value: Analytics
              resource_type: inventory.CloudService
          - concat:
              extend_data:
                label: All
              query:
                aggregate:
                - group:
                    fields:
                    - name: value
                      operator: count
                    keys:
                    - key: project_id
                      name: project_id
                    - key: cloud_service_type
                      name: cloud_service_type
                    - key: cloud_service_group
                      name: cloud_service_group
                    - key: provider
                      name: provider
                filter:
                - key: ref_cloud_service_type.is_primary
                  operator: eq
                  value: true
              resource_type: inventory.CloudService
          - concat:
              extend_data:
                label: Storage
              query:
                aggregate:
                - group:
                    fields:
                    - key: data.size
                      name: value
                      operator: sum
                    keys:
                    - key: project_id
                      name: project_id
                    - key: cloud_service_type
                      name: cloud_service_type
                    - key: cloud_service_group
                      name: cloud_service_group
                    - key: provider
                      name: provider
                filter:
                - key: ref_cloud_service_type.is_major
                  operator: eq
                  value: true
                - key: ref_cloud_service_type.labels
                  operator: eq
                  value: Storage
              resource_type: inventory.CloudService
      mode: EXEC
      verb:
        exec: add


