# deploy always
{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: spacectl-main-conf
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  main.yaml: |
		{{- toYaml .Values.main | nindent 4 }}
{{ end }}
