tasks:
  - name: Create Hyper Billing Provider
    id: hyperbilling_provider
    uses: "@modules/resource"
    spec:
      resource_type: identity.Provider
      data:
        domain_id: ${{ tasks.domain.output.domain_id }}
        name: Hyper Billing
        provider: hyperbilling
        capability:
          supported_schema: ['aws_hyperbilling']
        metadata:
          view:
            layouts:
              help:service_account:create:
                name: Creation Help
                options:
                  markdown:
                    en: '# Help for Hyperbilling Users


                      ## Find Your Hyperbilling API Credentials


                      To get Hyperbilling API Credentials, contact to MZC_billing@mz.co.kr

                      '
                type: markdown
        tags:
          color: '#004F99'
          icon: https://spaceone-custom-assets.s3.ap-northeast-2.amazonaws.com/console-assets/icons/megazone.svg
        template:
          service_account:
            schema: {}
      mode: EXEC
      verb:
        exec: create
