tasks:
  - name: Create Marketplace Repository
    id: marketplace
    uses: "@modules/resource"
    spec:
      resource_type: repository.Repository
      data:
        domain_id: ${{ tasks.domain.output.domain_id }}
        name: Official Marketplace 
        repository_type: remote
        endpoint: ${{ var.marketplace_endpoint }}
      mode: EXEC
      verb:
        exec: register
