tasks:
  - name: Create Marketplace Token
    id: marketplace_token
    uses: "@modules/resource"
    spec:
      resource_type: secret.Secret
      data:
        domain_id: ${{ tasks.domain.output.domain_id }}
        name: marketplace-token
        secret_type: CREDENTIALS
        data: 
          token: ${{ var.marketplace_token }}
      mode: EXEC
      verb:
        exec: create

  - name: Create Marketplace Repository
    id: marketplace
    uses: "@modules/resource"
    spec:
      resource_type: repository.Repository
      data:
        domain_id: ${{ tasks.domain.output.domain_id }}
        name: Official Marketplace 
        repository_type: remote
        endpoint: ${{ tasks.marketplace_endpoint }}
        version: v1
        secret_id: ${{ tasks.marketplace_token.output.secret_id }}
      mode: EXEC
      verb:
        exec: register

  - name: Create Domain Admin Role
    id: domain_admin_role
    uses: "modules/resource"
    spec:
      resource_type: identity.Role
      data:
        name: "Domain Admin"
        role_type: DOMAIN
        policies:
          - policy_type: MANAGED
            policy_id: ${{ var.domain_policy_id }}
        domain_id: ${{ tasks.domain.output.domain_id }}
      mode: EXEC
      verb:
        exec: create

  - name: Create Project Admin Role
    id: project_admin_role
    uses: "modules/resource"
    spec:
      resource_type: identity.Role
      data:
        name: "Project Admin"
        role_type: PROJECT
        policies:
          - policy_type: MANAGED
            policy_id: ${{ var.project_policy_id }}
        domain_id: ${{ tasks.domain.output.domain_id }}
      mode: EXEC
      verb:
        exec: create


