###############################
# DEFAULT 
###############################
enabled: true
image:
    name: spaceone/spacectl
    version: latest
imagePullPolicy: IfNotPresent

global:
  namespace: spaceone

skip_health_check: false

#############################################################
# WARNING
# enable domain: root (only one-time during installation)
# enable domain: user (for new user domains)
#############################################################

##########################
# Root Domain
##########################

#domain: root
#main:
#  import:
#    - /root/spacectl/apply/root_domain.yaml
#    - /root/spacectl/apply/marketplace.yaml
#    #- /root/spacectl/apply/hyperbilling.yaml          # for Hyper billing
#    #- /root/spacectl/apply/domain_role.yaml           # for Developer
#    #- /root/spacectl/apply/project_role.yaml          # for Developer
#    #- /root/spacectl/apply/schema.yaml                # for Developer
#    #- /root/spacectl/apply/register_plugins.yaml      # for Developer
#    #- /root/spacectl/apply/monitoring.yaml            # for Developer
#    #- /root/spacectl/apply/plugin_endpoint.yaml       # for Developer
#
#  var:
#    domain_name: root
#    domain_owner:
#      id: admin
#      password: AdministratoR1
#    user:
#      id: root_api_key
#    consul_server: spaceone-consul-server
#    marketplace_endpoint: grpc://repository.portal.spaceone.dev:50051
#  tasks: []


###################
# User Domain
# For ID/PW login, use local_domain.yaml
# For Oauth login, user oauth_domain.yaml
###################

#domain: user
#main:
#    import:
#      - /root/spacectl/apply/local_domain.yaml
#      - /root/spacectl/apply/statistics.yaml
#
#    var:
#      domain_name: xxx3
#      domain_owner: admin
#      domain_owner_password: Admin1234567890
#      oauth_plugin_id: plugin-e6b1b0bbacc6
#      oauth_plugin_version: "1.1"
#      oauth_plugin_domain: example.com
#      oauth_plugin_client_id: 111111111111111111111111111111111111111111111.apps.googleusercontent.com
#      project_admin_policy_type: MANAGED
#      project_admin_policy_id: policy-0386cce2730b
#      domain_admin_policy_type: MANAGED
#      domain_admin_policy_id: policy-0386cce2730b
#
#    tasks: []
