###############################
# DEFAULT 
###############################
enabled: true
image:
    name: spaceone/spacectl
    version: latest
imagePullPolicy: IfNotPresent

global:
  namespace: spaceone

skip_health_check: false

#############################################################
# WARNING
# enable domain: root (only one-time during installation)
# enable domain: user (for new user domains)
#############################################################

##########################
# Root Domain
##########################

#domain: root
#main:
#  import:
#    - /root/spacectl/apply/root_domain.yaml 
#    - /root/spacectl/apply/marketplace.yaml
#    - /root/spacectl/apply/role.yaml
#    - /root/spacectl/apply/hyperbilling.yaml # If you have a hyperbilling account
#  var:
#    domain_name: root
#    default_language: ko
#    default_timezone: Asia/Seoul
#    domain_owner:
#      id: admin
#      password: Adminpassword
#    user:
#      id: root_api_key
#    consul_server: spaceone-consul-server
#    marketplace_endpoint: grpc://repository.portal.spaceone.dev:50051
#    project_admin_policy_type: MANAGED
#    project_admin_policy_id: policy-managed-project-admin
#    project_viewer_policy_type: MANAGED
#    project_viewer_policy_id: policy-managed-project-viewer
#    domain_admin_policy_type: MANAGED
#    domain_admin_policy_id: policy-managed-domain-admin
#    domain_viewer_policy_type: MANAGED
#    domain_viewer_policy_id: policy-managed-domain-viewer
#  tasks: []

###################
# User Domain
# For ID/PW login, use local_domain.yaml
# For Oauth login, user oauth_domain.yaml
###################

#domain: user
#main:
#  import:
#    - /root/spacectl/apply/local_domain.yaml
#    - /root/spacectl/apply/statistics.yaml
#
#  var:
#    domain_name: spaceone
#    default_language: ko
#    default_timezone: Asia/Seoul
#    domain_owner: admin
#    domain_owner_password: Admin123!@#
#    project_admin_policy_id: policy-managed-project-admin
#    project_viewer_policy_id: policy-managed-project-viewer
#    domain_admin_policy_id: policy-managed-domain-admin
#    domain_viewer_policy_id: policy-managed-domain-viewer
#    project_admin_policy_type: MANAGED
#    project_admin_policy_id: policy-managed-project-admin
#    project_viewer_policy_type: MANAGED
#    project_viewer_policy_id: policy-managed-project-viewer
#    domain_admin_policy_type: MANAGED
#    domain_admin_policy_id: policy-managed-domain-admin
#    domain_viewer_policy_type: MANAGED
#    domain_viewer_policy_id: policy-managed-domain-viewer
#
#  tasks: []
